### ISSUE TITLE
Feature Request: YAML Anchors for required jobs for production

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/orb-starter-kit#15]
Create a YAML anchor containing the names of the integration tests triggered on the master branch. This makes it easier to reference in the promotion jobs further on when we need to ensure all tests have pasts before continuing the workflow.

Following this example from the slack orb: https://github.com/CircleCI-Public/slack-orb/blob/staging/.circleci/config.yml#L79

```
prod-deploy_requires: &prod-deploy_requires
  [
    job,
    names,
    here
  ]

..

# patch, minor, or major publishing
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          context: orb-publishing
          orb-name: circleci/slack
          cleanup-tags: true
          ssh-fingerprints: xxx
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/
```
